### PR TITLE
Consistency fixes

### PR DESCRIPTION
**Pull request by bassosimone**
This pull request contains a number of consistency fixes spanning naming conventions (of namespaces, of functions, of clasess, of headers) and it also removes unneded files.

All this stuff is grouped together to ease review. I guess it's not priority to merge this pull request now, but we should do this before making the stable release.

### CODE REVIEW

**Comment by hellais** [comment]
Can you rebase this against the current master?

**Comment by bassosimone** [comment]
Done!

**Comment by hellais** [comment]
Ok this looks good. Merging.

**Comment by bassosimone** [comment]
Thanks!

**Pull request merged**
