### PR TITLE
Make the connectivity check more robust using nexa.polito.it

### PR DESCRIPTION
**Pull request by alessandro40**
As @bassosimone suggested, a test based on github.com is not robust enough, since github.com could be blocked in some countries.

### CODE REVIEW

**Comment by alessandro40** [comment]
The DNS test fails on Travis. I will re-open this pull request after having fixed it.

**Comment by alessandro40** [comment]
Looking at the Travis log, I found out that the failure is not related to the effects of this pull request. So, I will re-open it, since it should be valid.

**Comment by bassosimone** [comment]
Thanks, @alessandro40. I have investigated the issue you reported regarding DNS IPv6 tests, it turns out that ooni.torproject.org changed IPv6 address. All of this should be fixed by #113. So, I suggest that you rebase you branch once #113 is merged and then git push -f such branch, so that we can review your pull request rebased on top of the new master including #113 and hopefully everyting works OK :).

**Comment by alessandro40** [comment]
Thanks, @bassosimone. As you suggested, I rebased my branch on the top of the new master and it has passed the Travis build.

**Comment by alessandro40** [comment]
The second commit is necessary to build libight on Android-ARM. The bug has been fixed by @bassosimone.

**Comment by bassosimone** [comment]
Thank you, merging.

**Pull request merged**
